# Uncomment this line to define a global platform for your project
platform :ios, ’10.2’

target 'CrazyIndeed' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrazyIndeed
pod 'Firebase', '>= 2.5.1'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FBSDKLoginKit'

end
